config/routes.rb
Rails.application.routes.draw do
  root 'mensagens#index'
  resources :mensagens
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mensagem.rb
class Mensagem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mensagens_controller.rb
class MensagensController < ApplicationController
  before_action :set_mensagem, only: %i[ show edit update destroy ]

  # GET /mensagens or /mensagens.json
  def index
    @mensagens = Mensagem.all
  end

  # GET /mensagens/1 or /mensagens/1.json
  def show
  end

  # GET /mensagens/new
  def new
    @mensagem = Mensagem.new
  end

  # GET /mensagens/1/edit
  def edit
  end

  # POST /mensagens or /mensagens.json
  def create
    @mensagem = Mensagem.new(mensagem_params)

    respond_to do |format|
      if @mensagem.save
        format.html { redirect_to @mensagem, notice: "Mensagem cadastrada com sucesso!" }
        format.json { render :show, status: :created, location: @mensagem }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mensagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mensagens/1 or /mensagens/1.json
  def update
    respond_to do |format|
      if @mensagem.update(mensagem_params)
        format.html { redirect_to @mensagem, notice: "Mensagem atualizada com sucesso!" }
        format.json { render :show, status: :ok, location: @mensagem }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mensagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mensagens/1 or /mensagens/1.json
  def destroy
    @mensagem.destroy
    respond_to do |format|
      format.html { redirect_to mensagens_url, notice: "Mensagem apagada com sucesso!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mensagem
      @mensagem = Mensagem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mensagem_params
      params.require(:mensagem).permit(:titulo, :corpo, :autor, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mensagens_helper.rb
module MensagensHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>Mural</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container rounded-corners">
    <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script> 
 </body>
</html>

app/views/mensagens/_form.html.erb
<%= simple_form_for @mensagem do |f| %>
  <%= f.input :titulo, label: 'Título', required: false %>
  <%= f.input :corpo, as: :text, required: false %> 
  <%= f.input :autor, required: false %> 
  <%= f.input :email, required: false %> 
  <%= f.button :submit, 'Enviar',class: 'btn-primary' %>
<% end %> 

app/views/mensagens/_notice.html.erb
<% if notice.present? %>
  <div id="notice" class="alert alert-primary" role="alert"><%= notice %></div>
<% end %>

app/views/mensagens/edit.html.erb
<div class="float-md-right btn-group">
 <%= link_to 'Detalhar', @mensagem, class: "btn btn-secondary" %>
 <%= link_to 'Voltar', mensagens_path, class: "btn btn-secondary" %>
</div>
<h1>Editar Mensagem</h1>
<%= render 'form' %>

app/views/mensagens/index.html.erb
<% if notice.present? %>
  <%= render partial: 'notice' %>
<% end %>

<div class="float-md-rigth">
  <%= link_to 'Nova Mensagem', new_mensagem_path, class: "btn btn-primary" %>
</div>

<h1>Mural de Mensagens</h1>

<% if @mensagens.empty? %>
  <p>Nenhuma mensagem encontrada.</p>
<% else %>
  <% @mensagens.each do |mensagem| %>
    <div class="card">
      <div class="card-header">
        <h5><%= mensagem.titulo %></h5>
      </div>
    <div class="card-body">
      <%= mensagem.corpo %>
    </div>
    <div class="card-footer">
      <div class="btn-group">
        <%= link_to 'Detalhar', mensagem, class: 'btn btn-secondary btn-sm' %>
        <%= link_to 'Editar', edit_mensagem_path(mensagem), class: 'btn btn-secondary btn-sm' %>
        <%= link_to 'Excluir', mensagem, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-secondary btn-sm' %>
      </div>
      <div class="float-md-rigth">
        <samll>Enviada por <%= mail_to mensagem.email, mensagem.autor %> em <%= mensagem.created_at.strftime("%d/%m/%Y") %></small>
      </div>
    </div>
  </div>
<% end %>
<% end %>

app/views/mensagens/new.html.erb
<div class="float-md-rigth">
  <%= link_to 'Voltar',new_mensagem_path, class: "btn btn-secondary" %>
</div>

<h1>Nova Mensagem</h1>

<%= render 'form' %>

app/views/mensagens/show.html.erb
<% if notice.present? %>
  <%= render partial: 'notice' %>
<% end %>

<div class="float-md-rigth btn-group">
  <%= link_to 'Voltar', mensagem_path, class: 'btn btn-secondary' %>
  <%= link_to 'Editar', edit_mensagem_path(@mensagem), class: 'btn btn-secondary' %>
  <%= link_to 'Excluir', @mensagem, method: :delete, data: { confirm: 'Tem certeza ?' }, class: 'btn btn-secondary' %>
</div>

<h1> Detalhar Mensagem</h1>

<div class="card">
  <div class="card-header">
    <h5><%= @mensagem.titulo %></h5>
  </div>
  <div class="card-body">
    <%= @mensagem.corpo %>
  </div>
  <div class="card-footer">
    <small>Enviada por <%= mail_to @mensagem.email, @mensagem.autor %> em <%= @mensagem.created_at.strftime("%d/%m/%Y") %></small>
  </div>
</div>